version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/productsearch/data
  
#  product-search:
#     container_name: product-search
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:80"
#     depends_on:
#       - db

volumes:
  db:
    driver: local